export enum UserErrors {
	NOT_FOUND = "USER_NOT_FOUND",
	EMAIL_ALREADY_EXISTS = "USER_EMAIL_ALREADY_EXISTS",
	INVALID_CREDENTIALS = "USER_INVALID_CREDENTIALS",
	UNAUTHORIZED = "USER_UNAUTHORIZED",
	ACCESS_DENIED = "USER_ACCESS_DENIED",
}
