export enum CategoryErrors {
	NOT_FOUND = "CATEGORY_NOT_FOUND",
	MANY_NOT_FOUND = "CATEGORIES_NOT_FOUND",
}

export enum SubcategoryErrors {
	NOT_FOUND = "SUBCATEGORY_NOT_FOUND",
	PARENT_NOT_FOUND = "PARENT_CATEGORY_NOT_FOUND",
	MANY_NOT_FOUND = "SUBCATEGORIES_NOT_FOUND",
}
