export enum OAuthErrors {
  PROVIDER_NOT_SUPPORTED = "OAUTH_PROVIDER_NOT_SUPPORTED",
  PROVIDER_MISCONFIGURED = "OAUTH_PROVIDER_MISCONFIGURED",
  INVALID_CALLBACK_CODE = "OAUTH_INVALID_CALLBACK_CODE",
  EMAIL_NOT_AVAILABLE = "OAUTH_EMAIL_NOT_AVAILABLE",
  EMAIL_NOT_VERIFIED = "OAUTH_EMAIL_NOT_VERIFIED",
  ACCOUNT_NOT_FOUND = "OAUTH_ACCOUNT_NOT_FOUND",
}
